model = "gpt-5.3-codex"
model_reasoning_effort = "xhigh"
reasoning_effort = "xhigh"
personality = "pragmatic"

model_provider = "cpa"


[projects."/Users/kqy/Documents/kqyCode/Workspace"]
trust_level = "trusted"


[features]
skills =true

[projects."/Users/kqy"]
trust_level = "trusted"

[projects."/Users/kqy/Documents/kqyCode/KQYAIRule"]
trust_level = "trusted"

[projects."/Users/kqy/Documents/kqyCode/Workspace/Apps/ReadingGraphApp"]
trust_level = "trusted"

[projects."/Users/kqy/Documents/kqyCode/Workspace/Apps/RubikBlindfoldAPP/RubikBlindfoldDomain"]
trust_level = "trusted"

[projects."/Users/kqy/Documents/kqyCode/Workspace/Apps/ReadingGraphApp/ReadingGraphDomain"]
trust_level = "trusted"

[projects."/Users/kqy/Documents"]
trust_level = "trusted"


[projects."/Users/kqy/.codex"]
trust_level = "trusted"

[model_providers.cpa]
name = "cpa"
# provider = "openai"
base_url = "http://localhost:8317/v1"
#base_url = "http://127.0.0.1:8317/v1"
#env_key = "sk-001"
wire_api = "responses"
# requires_openai_auth = true
requires_openai_auth = false

[model_providers.openrouter]
name = "Open Router"
base_url = "https://freeapi.dgbmc.top/"
env_key = "sk-nJg6KCLMyxehdDkI8yttvS5SPJ5RrPgTndpOEUcs1EyJXtEm"
wire_api = "responses"
query_params = {}


[model_providers.azure]
name = "Azure"
base_url = "https://ai.b1ank.top/v1"
env_key = "sk-oLtmrhBYPV0UVo3wp0doaMZoc7Cr6vJDrNdlbUAdefalisbf"  # Or "OPENAI_API_KEY", whichever you use.
query_params = { api-version = "2025-04-01-preview" }

[notice.model_migrations]
"gpt-5.2-codex" = "gpt-5.3-codex"
